Add patterns from other buildpack libraries

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,29 +1,42 @@
 #!/bin/bash
 
+# Heroku standard way to log buildpack info to console
+status() {
+  echo "-----> $*"
+}
+
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
+
 NGINX_VERSION=1.5.7
 PCRE_VERSION=8.21
 
 nginx_tarball_url=http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
 pcre_tarball_url=http://garr.dl.sourceforge.net/project/pcre/pcre/${PCRE_VERSION}/pcre-${PCRE_VERSION}.tar.bz2
 
+build_dir=$1
+cache_dir=$2
+env_dir=$3
 
-echo "Downloading $nginx_tarball_url"
+status "Downloading $nginx_tarball_url"
 curl -L $nginx_tarball_url | tar xzv
 
-echo "Downloading $pcre_tarball_url"
+status "Downloading $pcre_tarball_url"
 cd nginx-${NGINX_VERSION} && curl -L $pcre_tarball_url | tar xvj 
 
-# Compile nginx with final prefix
+status "Compiling nginx"
 cd nginx-${NGINX_VERSION}
 ./configure \
   --with-pcre=pcre-${PCRE_VERSION} \
   --prefix=/app/nginx \
   --with-http_ssl_module
+
+status "Installing nginx"
 make install
 
 # Copy the installation where it'll persist
-mv /app/nginx $1/nginx
+mv /app/nginx $build_dir/nginx
 
 # Add to PATH
-mkdir -p $1/.profile.d
-echo 'PATH=$PATH:$HOME/nginx/sbin' > $1/.profile.d/nginx_path.sh
+mkdir -p $build_dir/.profile.d
+echo 'PATH=$PATH:$HOME/nginx/sbin' > $build_dir/.profile.d/nginx_path.sh
